### ISSUE TITLE
Manhuaren extension http error 500

### ISSUE THREAD

**Issue by memphise** [inorichi/tachiyomi-extensions#1090]
BUGS:
 tachiyomi version r1504
 Manhuaren extension version 1.2.5

 manga link: https://www.manhuaren.com/m809589/

 open manga in my bookshelf from manhuaren,such as attack on titan("进击的巨人"), it toasted "tachiyomi : http error 500" ， I don't know the reason is that manhuren server api changed or it banned my ip?  But  i can read the manga by brower on PC 。

error log:

```
2019-05-08 12:11:12.343 24585-24720/eu.kanade.tachiyomi.debug I/chatty: uid=10205(eu.kanade.tachiyomi.debug) FinalizerDaemon identical 4 lines
2019-05-08 12:11:12.343 24585-24720/eu.kanade.tachiyomi.debug W/System: A resource failed to call close. 
2019-05-08 12:11:14.328 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Create view for MangaController@afc1a41
2019-05-08 12:11:14.348 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Attach view for MangaController@afc1a41
2019-05-08 12:11:14.359 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Create view for ChaptersController@1002072
2019-05-08 12:11:14.384 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Attach view for ChaptersController@1002072
2019-05-08 12:11:14.387 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Create view for MangaInfoController@533ff59
2019-05-08 12:11:14.443 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Attach view for MangaInfoController@533ff59
2019-05-08 12:11:14.829 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Detach view for LibraryController@1b883f6
2019-05-08 12:11:15.486 24585-24585/eu.kanade.tachiyomi.debug I/Timeline: Timeline: Activity_launch_request time:33679560 intent:Intent { cmp=eu.kanade.tachiyomi.debug/eu.kanade.tachiyomi.ui.reader.ReaderActivity (has extras) }
2019-05-08 12:11:15.519 24585-24585/eu.kanade.tachiyomi.debug W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@3d84f4a
2019-05-08 12:11:15.535 24585-24665/eu.kanade.tachiyomi.debug D/ViewContentFactory: initViewContentFetcherClass
2019-05-08 12:11:15.535 24585-24665/eu.kanade.tachiyomi.debug I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
2019-05-08 12:11:15.535 24585-24665/eu.kanade.tachiyomi.debug D/ViewContentFactory: createInterceptor took 0ms
2019-05-08 12:11:15.697 24585-24673/eu.kanade.tachiyomi.debug D/ChapterLoader$loadChapter: Loading pages for 第21话
2019-05-08 12:11:16.126 24585-24585/eu.kanade.tachiyomi.debug E/ReaderActivity: java.lang.Exception: HTTP error 500
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservableSuccess$1.call(OkHttpExtensions.kt:53)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservableSuccess$1.call(Unknown Source:2)
        at rx.internal.util.ActionObserver.onNext(ActionObserver.java:39)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:96)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:25)
        at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4$1.setProducer(OperatorOnErrorResumeNextViaFunction.java:130)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:45)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:13)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
        at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
        at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:188)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:98)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:25) 
        at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126) 
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4$1.setProducer(OperatorOnErrorResumeNextViaFunction.java:130) 
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) 
        at rx.Subscriber.setProducer(Subscriber.java:205) 
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:45) 
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:13) 
        at rx.Observable.unsafeSubscribe(Observable.java:10256) 
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) 
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) 
        at rx.Observable.unsafeSubscribe(Observable.java:10256) 
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
        at rx.Observable.unsafeSubscribe(Observable.java:10256) 
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142) 
        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212) 
        at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50) 
        at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33) 
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
        at rx.Observable.unsafeSubscribe(Observable.java:10256) 
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
        at rx.Observable.unsafeSubscribe(Observable.java:10256) 
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) 
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) 
        at rx.Observable.unsafeSubscribe(Observable.java:10256) 
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) 
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) 
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) 
        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224) 
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) 
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-05-08 12:11:16.189 24585-24585/eu.kanade.tachiyomi.debug I/Toast: Show toast from OpPackageName:eu.kanade.tachiyomi.debug, PackageName:eu.kanade.tachiyomi.debug
2019-05-08 12:11:44.867 24585-24585/eu.kanade.tachiyomi.debug W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
2019-05-08 12:11:45.618 24585-24585/eu.kanade.tachiyomi.debug D/ViewRootImpl[MainActivity]: changeCanvasOpacity: opaque=false
2019-05-08 12:11:45.889 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Detach view for MangaController@afc1a41
2019-05-08 12:11:45.889 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Detach view for ChaptersController@1002072
2019-05-08 12:11:45.890 24585-24585/eu.kanade.tachiyomi.debug D/BaseController: Detach view for MangaInfoController@533ff59
2019-05-08 12:11:46.108 24585-24585/eu.kanade.tachiyomi.debug D/ViewRootImpl[MainActivity]: changeCanvasOpacity: opaque=true
```

**Comment by memphise** [comment]
i uninstalled the manhuaren 1.2.5 and changed it back to version 1.2.4 , tachiyomi works well now
