### ISSUE TITLE
MangaDex 1.2.58 not installing correctly

### ISSUE THREAD

**Issue by paulo27ms** [inorichi/tachiyomi-extensions#1129]
Tachiyomi 0.8.4, android 4.1.2.
Today I noticed the extension got an update and when I tried to update, it downloaded and started the installation process but the installation didn't actually finish (I don't get the OK button at the end), when I closed Tachiyomi and opened it again the extension page still said there was an update, and that the version I had was 1.2.57.
I went into my settings and searched for the extension in my applications and it said there that it was 1.2.58, I force stopped it thinking that was the issue but when I went back to Tachiyomi the extension now showed in the not installed area and gave me the option to install it, which I tried but I got the same issue as when updating, installation doesn't complete and just exists back to Tachiyomi. 
Went back to my settings and uninstalled the extension from there and tried again, same thing happened with the extension not being moved to "Installed", what does seem to happen is that after trying to install through Tachiyomi, it actually installed on my phone but Tachiyomi can't seem to recognize it or something. I also don't have the option to force stop MangaDex in my application settings anymore.
I only have MangaSee installed now and even though that doesn't give me the option to force stop it like MangaDex, the extension works fine.

I noticed other extensions were also changed along with MangaDex's last commit and there was also entirely new extensions added but I tried installing those and they install and work properly.

**Comment by CarlosEsco** [comment]
1.2.57 is in the repo branch

**Comment by paulo27ms** [comment]
I think I editted my post as you posted yours. Thanks for pointing it out though.

**Comment by arkon** [comment]
What happens if you uninstall MangaDex and try to install it again?

**Comment by paulo27ms** [comment]
I just installed 1.2.57 and then uninstalled through Tachiyomi and the issue persists when trying to re-install to 1.2.58.
Reinstalled 1.2.57 again and uninstalled through settings menu, same thing (though this time I noticed that in 1.2.57 I don't get the option to force stop MangaDex anymore either, even though the extension was now working fine, so I guess that element isn't too important here).
Downloaded 1.2.58 from the repo branch, it now installed correctly (I got the OK at the end) but extension doesn't actually work and Tachiyomi still doesn't see it as installed.

One thing I did notice is that 1.2.58 is 2,50MB (think I saw it as 2,56MB before too?) while 1.2.57 is 156KB.
So I guess it has something to do with a corrupt installation.

**Comment by arkon** [comment]
Can you try 1.2.59?

**Comment by paulo27ms** [comment]
It installed and is recognized but now Tachiyomi crashes when I try to browser or update MangaDex manga (I can still read manga that I didn't download in my library).

**Comment by arkon** [comment]
Can you try getting the crash logs? https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android

**Comment by paulo27ms** [comment]
Unfortunately those steps do not work. After I press the button to make the report, it simply never comes.
I tried searching for logging apps but they seem to require root access (which I thought I had), I searched for some apps to attempt to and verify root and they tell me I'm rooted already so having some difficulty there. I can't connect my phone to my computer through USB either, it stopped working a while back and no new cable fixed it.
~~About time for a new phone.~~
Open to other suggestions.

**Comment by arkon** [comment]
Can you try [this APK](https://drive.google.com/open?id=1KSA7XztABHep2-Q9fnuj9CDuGdQyMhRO)?

**Comment by paulo27ms** [comment]
Still crashing in the same places.

**Comment by arkon** [comment]
Reproduced in an emulator running Android 4.1 (API 16):

```
05-24 22:45:20.983 2924-2986/eu.kanade.tachiyomi.debug E/ACRA: ACRA caught a IllegalStateException for eu.kanade.tachiyomi.debug
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.NoClassDefFoundError: eu.kanade.tachiyomi.extension.all.mangadex.Mangadex$buildCookies$1
        at eu.kanade.tachiyomi.extension.all.mangadex.Mangadex.buildCookies(Mangadex.kt:92)
        at eu.kanade.tachiyomi.extension.all.mangadex.Mangadex.cookiesHeader(Mangadex.kt:89)
        at eu.kanade.tachiyomi.extension.all.mangadex.Mangadex.access$cookiesHeader(Mangadex.kt:45)
        at eu.kanade.tachiyomi.extension.all.mangadex.Mangadex$clientBuilder$1.intercept(Mangadex.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at eu.kanade.tachiyomi.lib.ratelimit.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:55)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:23)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber$1.request(OperatorSubscribeOn.java:109)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.setProducer(OperatorSubscribeOn.java:105)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:45)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:13)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
    	at rx.internal.operators.OnSubscrib
```

**Comment by arkon** [comment]
Seems to work fine if the modules have their dependencies set to `compileOnly` instead of `implementation`. However, having the Kotlin stdlib set as `compileOnly` results in:

```
05-24 22:54:39.773 3405-3405/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: kotlin.jvm.internal.Intrinsics
        at eu.kanade.tachiyomi.extension.all.mangadex.MangadexUrlActivity.getQueryFromPathSegments(MangadexUrlActivity.kt)
        at eu.kanade.tachiyomi.lib.urlhandler.UrlHandlerActivity.onCreate(UrlHandlerActivity.kt:15)
        at android.app.Activity.performCreate(Activity.java:5008)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
        at android.app.ActivityThread.access$600(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by arkon** [comment]
I ended up just reverting the changes.
