### ISSUE TITLE
Socket error found while running Kafka

### ISSUE THREAD

**Issue by Susanjohn2893** [inorichi/tachiyomi-extensions#2364]
Getting the below error while running the kafka command,inistrator@localhost bin]$ ./kafka-server-start.sh ../config/server.properties
[2020-03-05 03:40:06,349] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2020-03-05 03:40:07,024] INFO starting (kafka.server.KafkaServer)
[2020-03-05 03:40:07,025] INFO Connecting to zookeeper on 10.0.3.124:2181 (kafka.server.KafkaServer)
[2020-03-05 03:40:07,042] INFO [ZooKeeperClient] Initializing a new session to 10.0.3.124:2181. (kafka.zookeeper.ZooKeeperClient)
[2020-03-05 03:40:07,079] INFO Client environment:zookeeper.version=3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03, built on 06/29/2018 00:39 GMT (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,079] INFO Client environment:host.name=localhost (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,079] INFO Client environment:java.version=1.8.0_131 (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,080] INFO Client environment:java.vendor=Oracle Corporation (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,080] INFO Client environment:java.home=/usr/java/jdk1.8.0_131/jre (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,080] INFO Client environment:java.class.path=/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/activation-1.1.1.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/aopalliance-repackaged-2.5.0-b42.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/argparse4j-0.7.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/audience-annotations-0.5.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/commons-lang3-3.5.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/compileScala.mapping:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/compileScala.mapping.asc:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/connect-api-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/connect-basic-auth-extension-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/connect-file-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/connect-json-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/connect-runtime-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/connect-transforms-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/guava-20.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/hk2-api-2.5.0-b42.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/hk2-locator-2.5.0-b42.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/hk2-utils-2.5.0-b42.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jackson-annotations-2.9.7.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jackson-core-2.9.7.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jackson-databind-2.9.7.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jackson-jaxrs-base-2.9.7.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jackson-jaxrs-json-provider-2.9.7.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jackson-module-jaxb-annotations-2.9.7.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/javassist-3.22.0-CR2.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/javax.annotation-api-1.2.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/javax.inject-1.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/javax.inject-2.5.0-b42.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/javax.servlet-api-3.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/javax.ws.rs-api-2.1.1.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/javax.ws.rs-api-2.1.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jaxb-api-2.3.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jersey-client-2.27.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jersey-common-2.27.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jersey-container-servlet-2.27.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jersey-container-servlet-core-2.27.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jersey-hk2-2.27.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jersey-media-jaxb-2.27.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jersey-server-2.27.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-client-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-continuation-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-http-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-io-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-security-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-server-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-servlet-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-servlets-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jetty-util-9.4.12.v20180830.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/jopt-simple-5.0.4.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka_2.12-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka_2.12-2.1.0-sources.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka-clients-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka-log4j-appender-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka-streams-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka-streams-examples-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka-streams-scala_2.12-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka-streams-test-utils-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/kafka-tools-2.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/log4j-1.2.17.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/lz4-java-1.5.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/maven-artifact-3.5.4.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/metrics-core-2.2.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/osgi-resource-locator-1.0.1.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/plexus-utils-3.1.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/reflections-0.9.11.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/rocksdbjni-5.14.2.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/scala-library-2.12.7.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/scala-logging_2.12-3.9.0.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/scala-reflect-2.12.7.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/slf4j-api-1.7.25.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/slf4j-log4j12-1.7.25.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/snappy-java-1.1.7.2.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/validation-api-1.1.0.Final.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/zkclient-0.10.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/zookeeper-3.4.13.jar:/home/administrator/Deployment/kafka_2.12-2.1.0/bin/../libs/zstd-jni-1.3.5-4.jar (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,081] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,082] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,082] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,082] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,082] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,082] INFO Client environment:os.version=3.10.0-957.el7.x86_64 (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,082] INFO Client environment:user.name=administrator (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,083] INFO Client environment:user.home=/home/administrator (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,083] INFO Client environment:user.dir=/home/administrator/Deployment/kafka_2.12-2.1.0/bin (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,086] INFO Initiating client connection, connectString=10.0.3.124:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@cd3fee8 (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:07,135] INFO Opening socket connection to server 10.0.3.124/10.0.3.124:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:07,135] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-03-05 03:40:07,146] INFO Socket error occurred: 10.0.3.124/10.0.3.124:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:08,257] INFO Opening socket connection to server 10.0.3.124/10.0.3.124:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:08,259] INFO Socket error occurred: 10.0.3.124/10.0.3.124:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:09,369] INFO Opening socket connection to server 10.0.3.124/10.0.3.124:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:09,370] INFO Socket error occurred: 10.0.3.124/10.0.3.124:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:10,480] INFO Opening socket connection to server 10.0.3.124/10.0.3.124:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:10,481] INFO Socket error occurred: 10.0.3.124/10.0.3.124:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:11,596] INFO Opening socket connection to server 10.0.3.124/10.0.3.124:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:11,597] INFO Socket error occurred: 10.0.3.124/10.0.3.124:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:12,707] INFO Opening socket connection to server 10.0.3.124/10.0.3.124:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:12,709] INFO Socket error occurred: 10.0.3.124/10.0.3.124:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:13,138] INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient)
[2020-03-05 03:40:13,820] INFO Opening socket connection to server 10.0.3.124/10.0.3.124:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:13,940] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
[2020-03-05 03:40:13,940] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
[2020-03-05 03:40:13,945] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
[2020-03-05 03:40:13,947] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:268)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:264)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:97)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1694)
	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:348)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:75)
	at kafka.Kafka.main(Kafka.scala)
[2020-03-05 03:40:13,965] INFO shutting down (kafka.server.KafkaServer)
[2020-03-05 03:40:13,988] INFO shut down completed (kafka.server.KafkaServer)
[2020-03-05 03:40:13,989] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[2020-03-05 03:40:14,005] INFO shutting down (kafka.server.KafkaServer)
[administrator@localhost bin]$

**Comment by CarlosEsco** [comment]
wrong repository?  we aren't Apache kafka
