### ISSUE TITLE
[Question] How to make app load extension

### ISSUE THREAD

**Issue by blackgin** [inorichi/tachiyomi-extensions#8]
I wrote an extension and I'm trying to make it work.
The problem that I encounter is that tachiyomi fails to load it. I also tried other extensions and they fail to load too.
This is the exception I get:
```
java.lang.ClassNotFoundException: eu.kanade.tachiyomi.extension.ru.mintmanga.Mintmanga
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:324)
     at eu.kanade.tachiyomi.source.SourceManager.loadExtension(SourceManager.kt:129)
     at eu.kanade.tachiyomi.source.SourceManager.createExtensionSources(SourceManager.kt:105)
     at eu.kanade.tachiyomi.source.SourceManager.createSources(SourceManager.kt:39)
     at eu.kanade.tachiyomi.source.SourceManager.<init>(SourceManager.kt:27)
     at eu.kanade.tachiyomi.AppModule$registerInjectables$6.invoke(AppModule.kt:31)
     at eu.kanade.tachiyomi.AppModule$registerInjectables$6.invoke(AppModule.kt:17)
     at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:171)
     at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:100)
     at uy.kohesive.injekt.api.InjektScope.getInstance(Scope.kt)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter$$special$$inlined$injectLazy$4.invoke(Injekt.kt:50)
     at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter.getSourceManager(LibraryPresenter.kt:0)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter.access$getSourceManager$p(LibraryPresenter.kt:34)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter$applyFilters$filterFn$1.invoke(LibraryPresenter.kt:141)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter$applyFilters$filterFn$1.invoke(LibraryPresenter.kt:34)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter.applyFilters(LibraryPresenter.kt:381)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter.access$applyFilters(LibraryPresenter.kt:34)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter$subscribeLibrary$1.invoke(LibraryPresenter.kt:113)
     at eu.kanade.tachiyomi.ui.library.LibraryPresenter$subscribeLibrary$1.invoke(LibraryPresenter.kt:34)
     at eu.kanade.tachiyomi.util.RxExtensionsKt$sam$Func2$3b9644a2.call(RxExtensions.kt:0)
     at rx.functions.Functions$3.call(Functions.java:88)
     at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.drain(OnSubscribeCombineLatest.java:275)
     at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.combine(OnSubscribeCombineLatest.java:226)
     at rx.internal.operators.OnSubscribeCombineLatest$CombinerSubscriber.onNext(OnSubscribeCombineLatest.java:375)
     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
     at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.drain(OnSubscribeCombineLatest.java:283)
     at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.combine(OnSubscribeCombineLatest.java:226)
     at rx.internal.operators.OnSubscribeCombineLatest$CombinerSubscriber.onNext(OnSubscribeCombineLatest.java:375)
     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
     at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
     at rx.internal.operators.OperatorOnBackpressureLatest$LatestEmitter.emit(OperatorOnBackpressureLatest.java:165)
     at rx.internal.operators.OperatorOnBackpressureLatest$LatestEmitter.onNext(OperatorOnBackpressureLatest.java:131)
     at rx.internal.operators.OperatorOnBackpressureLatest$LatestSubscriber.onNext(OperatorOnBackpressureLatest.java:211)
     at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
     at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onNext(OnSubscribeConcatMap.java:335)
     at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
     at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
     at com.pushtorefresh.storio.operations.internal.OnSubscribeExecuteAsBlocking.call(OnSubscribeExecuteAsBlocking.java:46)
     at com.pushtorefresh.storio.operations.internal.OnSubscribeExecuteAsBlocking.call(OnSubscribeExecuteAsBlocking.java:18)
     at rx.Observable.unsafeSubscribe(Observable.java:10144)
     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
     at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(OnSubscribeFromArray.java:100)
     at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:63)
     at rx.Subscriber.setProducer(Subscriber.java:211)
     at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
     at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
     at rx.Observable.unsafeSubscribe(Observable.java:10144)
     at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
     at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.Observable.unsafeSubscribe(Observable.java:10144)
     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "eu.kanade.tachiyomi.extension.ru.mintmanga.Mintmanga" on path: DexPathList[[zip file "/data/app/eu.kanade.tachiyomi.extension.ru.mintmanga-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 	... 67 more
 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "eu.kanade.tachiyomi.extension.ru.mintmanga.Mintmanga" on path: DexPathList[[zip file "/data/app/eu.kanade.tachiyomi.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/eu.kanade.tachiyomi.debug-1/lib/arm, /data/app/eu.kanade.tachiyomi.debug-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 		... 68 more
 		Suppressed: java.lang.ClassNotFoundException: Didn't find class "eu.kanade.tachiyomi.extension.ru.mintmanga.Mintmanga" on path: DexPathList[[dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-support-annotations-25.1.1_3aae8b2e22592569518fd6dfd5a5e91430f662ca-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-sqlite-1.12.1_6f578e29c4df7b4bb7c1fa6dee5fe362334f1bac-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-snake-yaml-v1.18-android_4942d2164064ef58be546a9c21a7a6a2f1712fa8-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-rxrelay-1.2.0_d1eae63e5feaef20251e4cf4f5bdf66831d032d4-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-rxjava-1.2.5_b4c58c5d2d93c13244743bb3fa1af7b2c5259eda-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-retrofit-2.1.0_1f944628c94a5a14fef39a3e5a126803bf1d7c7d-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-okio-1.11.0_0eb97f0845bc7c314f2311e7755aaa4adc103d8a-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-okhttp-3.5.0_9713ffda757ced74e19c0c0f374a2be9a5f1a2af-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-nucleus-3.0.0_80e527a8518007434d5d4a805e85a9a8da65829e-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-net.xpece.android-support-spinner-1.2.4_5a5bd16685d1acf523f7c3b6bbf911eb18f079e5-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-net.xpece.android-support-preference-1.2.2_a8253e09f618dd11212837b05134bdc6dbb41e23-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-net.vrallev.android-cat-1.0.5_e3ad6814f73deb168032f17dac2d1beec1140502-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-me.zhanghai.android.systemuihelper-library-1.0.0_dd2a34a971a18151a3c86ac19f56fadb90291508-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-me.zhanghai.android.materialprogressbar-library-1.3.0_af913cb48de0a2e6990e2b19455390fb90d488ec-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-kotson-2.5.0_9d06c948c2ba45107ab6688dc5fb294bf7c21092-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-kotlin-stdlib-1.0.6_4a0fde954ee233d82cfc974d49006eef3da35813-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-kotlin-runtime-1.0.6_bf20cb2ce6c76256f1353b9aa40d4b02ce773522-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-jsoup-1.10.2_d8e6dd8051a975aa489674f4e26e4d89c571df9b-classes.dex", dex file "/data/data/eu.kanade.tachiyomi.debug/files/instant-run/dex/slice-jp.wasabeef-glide-transformations-2.0.1_507bf05fa64e2e5586c24d53450aad1ba026d9fa-classes.dex", dex file "
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
     at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
     at com.android.tools.fd.runtime.IncrementalClassLoader.findClass(IncrementalClassLoader.java:62)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 			... 69 more
 			Suppressed: java.lang.ClassNotFoundException: eu.kanade.tachiyomi.extension.ru.mintmanga.Mintmanga
     at java.lang.Class.classForName(Native Method)
     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 				... 70 more
 			Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by inorichi** [comment]
Can you upload your compiled apk? Maybe it was compiled with proguard?

**Comment by blackgin** [comment]
My fork
https://github.com/blackgin/tachiyomi-extensions/tree/it-mangaeden
The apk
[it-mangaeden-debug.apk.zip](https://github.com/inorichi/tachiyomi-extensions/files/752863/it-mangaeden-debug.apk.zip)

**Comment by inorichi** [comment]
It loads in my emulator. Which version of tachiyomi are you using?

**Comment by blackgin** [comment]
I'm using 0.4.2 1098, built from my fork https://github.com/blackgin/tachiyomi

**Comment by blackgin** [comment]
I managed to make it work, instead of running the module from android studio, I did an assembleDebug and then manually installed the apk. It works this way.
Why won't in the other case?

**Comment by inorichi** [comment]
I never tried running the module from AS. In fact, I get an error saying "Default activity not found" when I try to use it.

I always compiled the apk with `Build > Build APK` and dragged the apk to the emulator or used `adb install -r my-catalog.apk` for my phone.

**Comment by blackgin** [comment]
I found out that it was Instant run's fault. I disabled it and now it appears to be working even by running it from AS.

You can run a project without activity by editing the configuration and setting Launch: Nothing.

![run_debug_configurations](https://cloud.githubusercontent.com/assets/231960/22625635/bcca5134-eb9c-11e6-9405-e11f5ef6b8d3.png)

**Comment by inorichi** [comment]
Oh, good to know.

Instant run doesn't play well with Kotlin, it may have improved since the last time I tried, but I always have it disabled and use `kotlin.incremental=true` in my global `gradle.properties`.
