### ISSUE TITLE
Developing new extension

### ISSUE THREAD

**Issue by karnadii** [inorichi/tachiyomi-extensions#922]
I tried to build a new extension, when I run it, I check the extensions page, and tap "trust" button on my new extension, but the extensions just disappear after i tap on trust. I can not test my ext now. any idea how to solve this?

i already follow CONTRIBUTING.md

**Comment by CarlosEsco** [comment]
You need to check the log cat. There is some install issue with the extension. Close tachiyomi then reopen and it will show the error in the logs

**Comment by karnadii** [comment]
```
03-17 19:30:16.213 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: Extension load error: Komik.
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: java.lang.ClassNotFoundException: eu.kanade.tachiyomi.extension.id.komik.Komik
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.Class.classForName(Native Method)
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.Class.forName(Class.java:324)
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtension(ExtensionLoader.kt:135)
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtensionFromPkgName(ExtensionLoader.kt:78)
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at eu.kanade.tachiyomi.extension.ExtensionManager$trustSignature$1$doResume$$inlined$map$lambda$1.doResume(ExtensionManager.kt:244)
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
03-17 19:30:16.214 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1388)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:251)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:845)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1674)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1629)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: Caused by: java.lang.ClassNotFoundException: Didn't find class "eu.kanade.tachiyomi.extension.id.komik.Komik" on path: DexPathList[[zip file "/data/app/eu.kanade.tachiyomi.extension.id.komik-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: 	... 14 more
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "eu.kanade.tachiyomi.extension.id.komik.Komik" on path: DexPathList[[zip file "/data/app/eu.kanade.tachiyomi.debug-1/base.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_dependencies_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_0_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_1_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_2_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_3_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_4_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_5_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_6_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_7_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_8_apk.apk", zip file "/data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/eu.kanade.tachiyomi.debug-1/lib/arm64, /data/app/eu.kanade.tachiyomi.debug-1/base.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/eu.kanade.tachiyomi.debug-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: 		... 15 more
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: 		Suppressed: java.lang.ClassNotFoundException: eu.kanade.tachiyomi.extension.id.komik.Komik
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.Class.classForName(Native Method)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: 			... 16 more
03-17 19:30:16.215 19078-19622/eu.kanade.tachiyomi.debug E/ExtensionLoader: 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```
any idea? I just copy existing extension then rename everything. there is no different from any other extension

**Comment by CarlosEsco** [comment]
You class name in Gradle and your package naming/class name in the actual class don't match or are wrong.  Look at other sources for samples

**Comment by karnadii** [comment]
my package name `package eu.kanade.tachiyomi.extension.id.komik` my class name is `Komik`
build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

ext {
    appName = 'Tachiyomi: Komik'
    pkgNameSuffix = 'id.komik'
    extClass = '.Komik'
    extVersionCode = 2
    libVersion = '1.0'
}

apply from: "$rootDir/common.gradle"

```

**Comment by CarlosEsco** [comment]
You gonna have to figure it out but stacktracd is showing it's not finding the class

java. lang.classNot FoundException: eu.kanade.tachiyomi.extension. id. komik.Komik

**Comment by karnadii** [comment]
i found a solution, my code is fine, https://stackoverflow.com/questions/22399572/java-lang-classnotfoundexception-didnt-find-class-on-path-dexpathlist
